## 配置文件
#创建项目相关表的后缀编号
#project_no=1

#郎坤API地址
#郎坤API测试环境地址
#LKAPIURL=http://60.205.218.71/Liems/webservice
#郎坤API生产环境地址
#LKAPIURL=http://47.94.91.246/Liems/webservice
#服务器API生产环境地址
LKAPIURL=http://localhost:8080/BIMAPI

#BIMAPI本机环境地址
#BIMAPIURL=http://localhost:8085/BIMAPI

#BIMAPI测试环境地址
#BIMAPIURL=http://60.205.218.71:8090/BIMAPI

#BIMAPI生产环境地址
BIMAPIURL=http://localhost:8080/BIMAPI