#database settings

#PPAS-localhost
#jdbc.driver=com.edb.Driver
#jdbc.url=jdbc\:edb\://localhost\:5445/test1
#jdbc.username=enterprisedb
#jdbc.password=000000

#PPAS-Test
#jdbc.driver=com.edb.Driver
#jdbc.url=jdbc\:edb\://60.205.218.71\:5444/bim_test
#jdbc.username=bim_test
#jdbc.password=bim_test

#Local postgres
jdbc.driver=org.postgresql.Driver
jdbc.url=jdbc:postgresql://192.168.199.99:5432/bim
jdbc.username=postgres
jdbc.password=A111111

#PPAS-Product
#jdbc.driver =org.postgresql.Driver
#jdbc.url =jdbc:postgresql://60.205.218.71:5444/bim_test2
#jdbc.username=bim_test
#jdbc.password=bim_test
dbcp.initialSize=50
dbcp.maxActive=200
dbcp.minIdle=30